### ISSUE TITLE
Add shapes to show relationship information

### ISSUE THREAD

**Issue by VAISHALI-DHANOA** [JKU-ICG/fuzzy-spreadsheet#19]

**Comment by ConnyWalchshofer** [comment]
Change visual encoding to vertical lines instead of arrow indication for input/output.

**Input/Output encoding**
Input cell encoding: left cell side
Output cell encoding: right cell side 

**Neighbourhood**
First degree: solid line, RGB (38,38,38)
Second degree: squared dot line, RGB (127,127,127)
Third degree: round dot line, RGB (191,191,191)

![image](https://user-images.githubusercontent.com/22545084/75160801-fdf9e380-571a-11ea-8acb-3ea02a56cf84.png)
